CREATE TABLE IF NOT EXISTS user_notification (
    id BIGINT NOT NULL PRIMARY KEY,
    userId BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(128) NOT NULL,
    content VARCHAR(1024) NOT NULL,
    targetPath VARCHAR(255) DEFAULT NULL,
    isRead TINYINT NOT NULL DEFAULT 0,
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete TINYINT NOT NULL DEFAULT 0,
    INDEX idx_user_notification_user_time (userId, createTime)
) COMMENT='用户站内通知';
